spring.application.name=samplewebooooo
server.port=8080
rakuten.api.format=json

# ✅ APIキーはソースコードに書かず、ここで管理する
rakuten.api.base-url=https://openapi.rakuten.co.jp/engine/api/Travel/SimpleHotelSearch/20170426
rakuten.api.application-id=43e9cbc8-2097-47bc-b9f4-f3e876b0aa44
rakuten.api.access-key=pk_Yw6kQbJNqr9TE02lFyfdP9b1qwgpKB8GFOSfriw51Yn



