spring.application.name=samplewebooooo
server.port=8080
rakuten.api.format=json

# ✅ APIキーはソースコードに書かず、ここで管理する
yahoo.api.base-url=https://shopping.yahooapis.jp/ShoppingWebService/V3/itemSearch
yahoo.api.client-id=dmVyPTIwMjUwNyZpZD1JZ0J1QXlKWEVCJmhhc2g9T1dVeU0ySTBOV1l3WmpoaFpUUXpPQQ
yahoo.api.secret-code=iqhDyk6Rij6Ph4KyHm8yaB6tzKNCeUx5V8oudsck

downloader.path=/vol2/user/missav
downloader.proxy=
downloader.timeout=15
downloader.domain=missav.com

# <button type="button" class="plyr__control plyr__control--overlaid" data-plyr="play" aria-label="Play"><svg aria-hidden="true" focusable="false">

# <use xlink:href="#plyr-play"></use></svg><span class="plyr__sr-only">Play</span></button> #

# plyr-play #
#
#
#
#