spring.application.name=samplewebooooo
server.port=8080
rakuten.api.base-url=https://openapi.rakuten.co.jp/engine/api/Travel/SimpleHotelSearch/20170426
rakuten.api.application-id=163caa68-0a55-4fd6-a19a-af123b5f06c1
https://openapi.rakuten.co.jp/engine/api/Travel/SimpleHotelSearch/20170426?format=json&largeClassCode=japan&middleClassCode=okinawa&smallClassCode=nahashi&applicationId=38b19d1d-ec63-4943-a140-4545136cc894&accessKey=pk_lmHro6umEWaHXqXt2ppguhr5zEPHLJVQX5Ws31HDmwh
rakuten.api.format=json

